<?php
/**
 *
 *  @copyright 2008 - https://www.clicshopping.org
 *  @Brand : ClicShopping(Tm) at Inpi all right Reserved
 *  @Licence GPL 2 & MIT
 *  @licence MIT - Portion of osCommerce 2.4
 *  @Info : https://www.clicshopping.org/forum/trademark/
 *
 */

  use ClicShopping\OM\Registry;
  use ClicShopping\OM\CLICSHOPPING;

  class co_contact_us_openstreetmap {
    public $code;
    public $group;
    public $title;
    public $description;
    public $sort_order;
    public $enabled = false;

    public function __construct() {
      $this->code = get_class($this);
      $this->group = basename(__DIR__);

      $this->title = CLICSHOPPING::getDef('module_contact_us_open_street_map_title');
      $this->description = CLICSHOPPING::getDef('module_contact_us_open_street_map_description');

      if (defined('MODULES_CONTACT_US_OPENSTREETMAP_STATUS')) {
        $this->sort_order = (int)MODULES_CONTACT_US_OPENSTREETMAP_SORT_ORDER;
        $this->enabled = (MODULES_CONTACT_US_OPENSTREETMAP_STATUS == 'True');
      }
    }

    public function execute() {

      $CLICSHOPPING_Template = Registry::get('Template');

      if (isset($_GET['Info']) && isset($_GET['Contact']) && !isset($_GET['Success'])) {

        $content_width = (int)MODULES_CONTACT_US_OPENSTREETMAP_CONTENT_WIDTH;

        $header_tag = '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.4.0/leaflet.css">';

        $CLICSHOPPING_Template->addBlock($header_tag, 'header_tags');

        $footer_tag = '<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.4.0/leaflet.js"></script>';
        $footer_tag .= '
          <script language="javascript">
            function init() {
               var map = new L.Map(\'map\');                       
                      
              L.tileLayer(\'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png\', {
                  attribution: \'&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors\',
                  maxZoom: ' . MODULES_CONTACT_US_OPENSTREETMAP_MAX_ZOOM . '
               }).addTo(map);
               map.attributionControl.setPrefix(\'\'); // Don\'t show the \'Powered by Leaflet\' text.
      
               var london = new L.LatLng(' . MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE . ', ' . MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE . '); 
               map.setView(london, ' . (int)MODULES_CONTACT_US_OPENSTREETMAP_VIEW . ');
               
               // Define an array. This could be done in a seperate js file.
               // This tidy formatted section could even be generated by a server-side script
               // or fetched seperately as a jsonp request.
               var markers = [
                  [ ' . MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE . ', ' . MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE . ', "' . MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS . '"],
               ';

        if (!empty(MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE_1)) {
          $footer_tag .= '
              [ ' . MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE_1 . ', ' . MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE_1 . ', "' . MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS_ANNEXE_1 . '" ],
          ';
        }

        if (!empty(MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE_1)) {
          $footer_tag .= '
              [ ' . MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE_2 . ', ' . MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE_2 . ', "' . MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS_ANNEXE_2 . '" ]
          ';
        }

        $footer_tag .= '
         ];
         //Loop through the markers array
         for (var i=0; i<markers.length; i++) {
           
            var lon = markers[i][0];
            var lat = markers[i][1];
            var popupText = markers[i][2];
            
             var markerLocation = new L.LatLng(lat, lon);
             var marker = new L.Marker(markerLocation);
             map.addLayer(marker);
         
             marker.bindPopup(popupText);         
         }
      }
    </script>
';

        $CLICSHOPPING_Template->addBlock($footer_tag, 'footer_scripts');

        $contact_us_map = '<!--  contact_us_openstreetmap start -->' . "\n";
        ob_start();
        require_once($CLICSHOPPING_Template->getTemplateModules($this->group . '/content/contact_us_openstreetmap'));

        $contact_us_map .= ob_get_clean();
        $contact_us_map .= '<!-- contact_us_openstreetmap end -->' . "\n";

        $CLICSHOPPING_Template->addBlock($contact_us_map, $this->group);
      }
    }

    public function isEnabled() {
      return $this->enabled;
    }

    public function check() {
      return defined('MODULES_CONTACT_US_OPENSTREETMAP_STATUS');
    }


    public function install() {
      $CLICSHOPPING_Db = Registry::get('Db');


      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Do you want activate this module ?',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_STATUS',
          'configuration_value' => 'True',
          'configuration_description' => 'Do you want activate this module  ?',
          'configuration_group_id' => '6',
          'sort_order' => '1',
          'set_function' => 'clic_cfg_set_boolean_value(array(\'True\', \'False\'))',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please select the width of the module ?',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_CONTENT_WIDTH',
          'configuration_value' => '12',
          'configuration_description' => 'Select a number between 1 and 12',
          'configuration_group_id' => '6',
          'sort_order' => '1',
          'set_function' => 'clic_cfg_set_content_module_width_pull_down',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please select the  length of the map',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_VIEW',
          'configuration_value' => '6',
          'configuration_description' => 'Please, indicate a number',
          'configuration_group_id' => '6',
          'sort_order' => '2',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please indicate the search deep',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_MAX_ZOOM',
          'configuration_value' => '90',
          'configuration_description' => 'Indicate a number',
          'configuration_group_id' => '6',
          'sort_order' => '2',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Name, address, country and company phone',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS',
          'configuration_value' => '',
          'configuration_description' => 'Name, address, country and company phone',
          'configuration_group_id' => '6',
          'sort_order' => '7',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please, indicate the latitude of your company',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE',
          'configuration_value' => '47.000',
          'configuration_description' => 'Indicate the latitude of your company',
          'configuration_group_id' => '6',
          'sort_order' => '3',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please, indicate the longitude of your company',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE',
          'configuration_value' => '-0.1213',
          'configuration_description' => 'Indicate the longitude of your company',
          'configuration_group_id' => '6',
          'sort_order' => '4',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Name, address, country and company phone (1st)',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS_ANNEXE_1',
          'configuration_value' => '',
          'configuration_description' => 'Name, address, country and company phone (1st)',
          'configuration_group_id' => '6',
          'sort_order' => '7',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please, indicate the latitude of your company (1st)',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE_1',
          'configuration_value' => '47.5056',
          'configuration_description' => 'Indicate the latitude of your company (1st)',
          'configuration_group_id' => '6',
          'sort_order' => '5',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please, indicate the longitude of your company (1st)',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE_1',
          'configuration_value' => '-0.1244324',
          'configuration_description' => 'Indicate the longitude of your company (1st)',
          'configuration_group_id' => '6',
          'sort_order' => '6',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Name, address, country and company phone (2nd)',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS_ANNEXE_2',
          'configuration_value' => '',
          'configuration_description' => 'Name, address, country and company phone (2nd)',
          'configuration_group_id' => '6',
          'sort_order' => '7',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );



      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please, indicate the latitude of your company (2nd)',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE_2',
          'configuration_value' => '47.5056',
          'configuration_description' => 'Indicate the latitude of your company (2nd)',
          'configuration_group_id' => '6',
          'sort_order' => '8',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please, indicate the longitude of your company (2nd)',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE_2',
          'configuration_value' => '0.119623',
          'configuration_description' => 'Indicate the longitude of your company (2nd)',
          'configuration_group_id' => '6',
          'sort_order' => '6',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Please indicate the map width',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_HEIGHT',
          'configuration_value' => '250',
          'configuration_description' => 'Please indicate the map width in pixel (without px)',
          'configuration_group_id' => '6',
          'sort_order' => '7',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );

      $CLICSHOPPING_Db->save('configuration', [
          'configuration_title' => 'Sort order',
          'configuration_key' => 'MODULES_CONTACT_US_OPENSTREETMAP_SORT_ORDER',
          'configuration_value' => '20',
          'configuration_description' => 'Sort order of display. Lowest is displayed first',
          'configuration_group_id' => '6',
          'sort_order' => '15',
          'set_function' => '',
          'date_added' => 'now()'
        ]
      );
    }

    public function remove() {
      return Registry::get('Db')->exec('delete from :table_configuration where configuration_key in ("' . implode('", "', $this->keys()) . '")');
    }

    public function keys() {
      return array('MODULES_CONTACT_US_OPENSTREETMAP_STATUS',
                   'MODULES_CONTACT_US_OPENSTREETMAP_CONTENT_WIDTH',
                   'MODULES_CONTACT_US_OPENSTREETMAP_VIEW',
                   'MODULES_CONTACT_US_OPENSTREETMAP_MAX_ZOOM',
                   'MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS',
                   'MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE',
                   'MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE',
                   'MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS',
                   'MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS_ANNEXE_1',
                   'MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE_1',
                   'MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE_1',
                   'MODULES_CONTACT_US_OPENSTREETMAP_STORE_ADDRESS_ANNEXE_2',
                   'MODULES_CONTACT_US_OPENSTREETMAP_LATITUDE_2',
                   'MODULES_CONTACT_US_OPENSTREETMAP_LONGITUDE_2',
                   'MODULES_CONTACT_US_OPENSTREETMAP_HEIGHT',
                   'MODULES_CONTACT_US_OPENSTREETMAP_SORT_ORDER'
                  );
    }
  }
